import { Job, Candidate, HumanReview, AuditLog } from '@/types';

export const INITIAL_JOBS: Job[] = [
  {
    id: 'vaga-01',
    title: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    area: 'Frontend',
    level: 'Sênior',
    minExperienceYears: 5,
    description: 'Buscamos desenvolvedor Frontend Sênior com sólida experiência no ecossistema React, Next.js (App Router), TypeScript e arquitetura de componentes escaláveis.',
    skills: [
      { id: 'sk-1', name: 'React', weight: 30, required: true },
      { id: 'sk-2', name: 'Next.js', weight: 25, required: true },
      { id: 'sk-3', name: 'TypeScript', weight: 20, required: true },
      { id: 'sk-4', name: 'Tailwind CSS', weight: 15, required: false },
      { id: 'sk-5', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'vaga-02',
    title: 'Engenheiro Backend Node.js Pleno',
    area: 'Backend',
    level: 'Pleno',
    minExperienceYears: 3,
    description: 'Responsável por projetar e desenvolver APIs RESTful e GraphQL de alto desempenho, modelagem de banco de dados relacional e integração com mensageria.',
    skills: [
      { id: 'sk-6', name: 'Node.js', weight: 30, required: true },
      { id: 'sk-7', name: 'TypeScript', weight: 25, required: true },
      { id: 'sk-8', name: 'SQL', weight: 20, required: true },
      { id: 'sk-9', name: 'Docker', weight: 15, required: false },
      { id: 'sk-10', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-18T14:30:00Z',
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'vaga-03',
    title: 'Engenheiro de Dados Pleno (Python / Spark / SQL)',
    area: 'Data & Analytics',
    level: 'Pleno',
    minExperienceYears: 3,
    description: 'Atuação na construção de pipelines de dados ETL/ELT robustos, estruturação de data lakes e garantia de qualidade de dados.',
    skills: [
      { id: 'sk-11', name: 'Python', weight: 30, required: true },
      { id: 'sk-12', name: 'SQL', weight: 25, required: true },
      { id: 'sk-13', name: 'Spark', weight: 20, required: true },
      { id: 'sk-14', name: 'Airflow', weight: 15, required: false },
      { id: 'sk-15', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-20T09:15:00Z',
    updatedAt: '2026-08-20T09:15:00Z',
  },
  {
    id: 'vaga-04',
    title: 'Especialista DevOps / Cloud (Kubernetes & AWS)',
    area: 'DevOps / Cloud',
    level: 'Especialista',
    minExperienceYears: 6,
    description: 'Liderança técnica na infraestrutura cloud, automação de esteiras CI/CD, monitoramento e observabilidade, e governança de clusters Kubernetes.',
    skills: [
      { id: 'sk-16', name: 'Kubernetes', weight: 30, required: true },
      { id: 'sk-17', name: 'Docker', weight: 25, required: true },
      { id: 'sk-18', name: 'Terraform', weight: 20, required: true },
      { id: 'sk-19', name: 'AWS', weight: 15, required: false },
      { id: 'sk-20', name: 'CI/CD', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-08-22T11:00:00Z',
  },
  {
    id: 'vaga-05',
    title: 'Desenvolvedor Full Stack Júnior (Web)',
    area: 'Full Stack',
    level: 'Júnior',
    minExperienceYears: 1,
    description: 'Oportunidade para profissionais em início de carreira para atuar no desenvolvimento de telas e integração com APIs na plataforma web da empresa.',
    skills: [
      { id: 'sk-21', name: 'JavaScript', weight: 35, required: true },
      { id: 'sk-22', name: 'React', weight: 25, required: true },
      { id: 'sk-23', name: 'Node.js', weight: 20, required: true },
      { id: 'sk-24', name: 'SQL', weight: 10, required: false },
      { id: 'sk-25', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-25T16:45:00Z',
    updatedAt: '2026-08-25T16:45:00Z',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-01',
    name: 'Lucas Andrade',
    email: 'l***e@email.com',
    phone: '(11) 9****-1234',
    experienceYears: 6,
    level: 'Sênior',
    technicalSkills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Git', 'Docker', 'GraphQL'],
    bio: 'Desenvolvedor Frontend Sênior com experiência em design systems, Server Components e Next.js.',
    resumeFileName: 'curriculo_lucas_andrade.pdf',
    resumeFileSize: 1420500,
    resumeUploadedAt: '2026-08-26T08:30:00Z',
    hasResume: true,
    createdAt: '2026-08-26T08:30:00Z',
    updatedAt: '2026-08-26T08:30:00Z',
  },
  {
    id: 'cand-02',
    name: 'Mariana Costa',
    email: 'm***a@email.com',
    phone: '(21) 9****-5678',
    experienceYears: 4,
    level: 'Pleno',
    technicalSkills: ['React', 'Next.js', 'TypeScript', 'Git', 'JavaScript', 'CSS3'],
    bio: 'Desenvolvedora Frontend com foco em interfaces acessíveis e responsivas.',
    resumeFileName: 'curriculo_mariana_costa.pdf',
    resumeFileSize: 980400,
    resumeUploadedAt: '2026-08-26T09:10:00Z',
    hasResume: true,
    createdAt: '2026-08-26T09:10:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'cand-03',
    name: 'Rodrigo Silveira',
    email: 'r***a@email.com',
    phone: '(31) 9****-9012',
    experienceYears: 3,
    level: 'Pleno',
    technicalSkills: ['React', 'TypeScript', 'Git', 'JavaScript', 'HTML5'],
    bio: 'Desenvolvedor Frontend focado em SPAs e integração de serviços.',
    resumeFileName: 'curriculo_rodrigo_silveira.pdf',
    resumeFileSize: 850200,
    resumeUploadedAt: '2026-08-26T10:05:00Z',
    hasResume: true,
    createdAt: '2026-08-26T10:05:00Z',
    updatedAt: '2026-08-26T10:05:00Z',
  },
  {
    id: 'cand-04',
    name: 'Camila Duarte',
    email: 'c***e@email.com',
    phone: '(41) 9****-3456',
    experienceYears: 2,
    level: 'Júnior',
    technicalSkills: ['JavaScript', 'HTML5', 'CSS3', 'Git', 'React'],
    bio: 'Desenvolvedora Web júnior com projetos em React e JavaScript vanilla.',
    resumeFileName: 'curriculo_camila_duarte.pdf',
    resumeFileSize: 720000,
    resumeUploadedAt: '2026-08-26T11:20:00Z',
    hasResume: true,
    createdAt: '2026-08-26T11:20:00Z',
    updatedAt: '2026-08-26T11:20:00Z',
  },
  {
    id: 'cand-05',
    name: 'Felipe Alcântara',
    email: 'f***a@email.com',
    phone: '(51) 9****-7890',
    experienceYears: 4,
    level: 'Pleno',
    technicalSkills: ['Node.js', 'TypeScript', 'SQL', 'Docker', 'Git', 'PostgreSQL', 'Express'],
    bio: 'Backend Engineer com foco em APIs resilientes, microserviços e bancos SQL.',
    resumeFileName: 'curriculo_felipe_alcantara.pdf',
    resumeFileSize: 1100300,
    resumeUploadedAt: '2026-08-27T08:00:00Z',
    hasResume: true,
    createdAt: '2026-08-27T08:00:00Z',
    updatedAt: '2026-08-27T08:00:00Z',
  },
  {
    id: 'cand-06',
    name: 'Beatriz Mendes',
    email: 'b***s@email.com',
    phone: '(61) 9****-2345',
    experienceYears: 3,
    level: 'Pleno',
    technicalSkills: ['Node.js', 'TypeScript', 'SQL', 'Git', 'REST'],
    bio: 'Desenvolvedora Backend Node.js atuando com arquitetura REST e testes automatizados.',
    resumeFileName: 'curriculo_beatriz_mendes.pdf',
    resumeFileSize: 890000,
    resumeUploadedAt: '2026-08-27T09:40:00Z',
    hasResume: true,
    createdAt: '2026-08-27T09:40:00Z',
    updatedAt: '2026-08-27T09:40:00Z',
  },
  {
    id: 'cand-07',
    name: 'Gabriel Rocha',
    email: 'g***a@email.com',
    phone: '(71) 9****-6789',
    experienceYears: 2,
    level: 'Júnior',
    technicalSkills: ['Node.js', 'JavaScript', 'SQL', 'Git'],
    bio: 'Desenvolvedor backend júnior com foco em banco de dados e APIs em Node.',
    resumeFileName: 'curriculo_gabriel_rocha.pdf',
    resumeFileSize: 650000,
    resumeUploadedAt: '2026-08-27T10:15:00Z',
    hasResume: true,
    createdAt: '2026-08-27T10:15:00Z',
    updatedAt: '2026-08-27T10:15:00Z',
  },
  {
    id: 'cand-08',
    name: 'Larissa Ramos',
    email: 'l***s@email.com',
    phone: '(81) 9****-0123',
    experienceYears: 5,
    level: 'Sênior',
    technicalSkills: ['Python', 'SQL', 'Spark', 'Airflow', 'Git', 'AWS', 'Data Modeling'],
    bio: 'Engenheira de dados especializada em processamento distribuído com PySpark e orquestração Airflow.',
    resumeFileName: 'curriculo_larissa_ramos.pdf',
    resumeFileSize: 1350000,
    resumeUploadedAt: '2026-08-28T09:00:00Z',
    hasResume: true,
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'cand-09',
    name: 'Thiago Neves',
    email: 't***s@email.com',
    phone: '(19) 9****-4567',
    experienceYears: 7,
    level: 'Especialista',
    technicalSkills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'CI/CD', 'Linux', 'Ansible'],
    bio: 'Especialista Cloud & DevOps focado em infraestrutura declarativa e resiliência de clusters.',
    resumeFileName: 'curriculo_thiago_neves.pdf',
    resumeFileSize: 1600000,
    resumeUploadedAt: '2026-08-28T10:30:00Z',
    hasResume: true,
    createdAt: '2026-08-28T10:30:00Z',
    updatedAt: '2026-08-28T10:30:00Z',
  },
  {
    id: 'cand-10',
    name: 'Juliana Peixoto',
    email: 'j***o@email.com',
    phone: '(85) 9****-8901',
    experienceYears: 1,
    level: 'Júnior',
    technicalSkills: ['JavaScript', 'React', 'Node.js', 'Git', 'HTML5', 'CSS3'],
    bio: 'Desenvolvedora Full Stack iniciante apaixonada por React e Node.js.',
    resumeFileName: 'curriculo_juliana_peixoto.pdf',
    resumeFileSize: 740000,
    resumeUploadedAt: '2026-08-29T14:00:00Z',
    hasResume: true,
    createdAt: '2026-08-29T14:00:00Z',
    updatedAt: '2026-08-29T14:00:00Z',
  },
  {
    id: 'cand-11',
    name: 'Diego Martins',
    email: 'd***s@email.com',
    phone: '(48) 9****-2345',
    experienceYears: 5,
    level: 'Sênior',
    technicalSkills: ['Java', 'Spring Boot', 'Oracle DB', 'Kafka', 'Microservices'],
    bio: 'Desenvolvedor Java/Spring enterprise com sólida base em sistemas bancários.',
    resumeFileName: 'curriculo_diego_martins.pdf',
    resumeFileSize: 920000,
    resumeUploadedAt: '2026-08-29T15:20:00Z',
    hasResume: true,
    createdAt: '2026-08-29T15:20:00Z',
    updatedAt: '2026-08-29T15:20:00Z',
  },
  {
    id: 'cand-12',
    name: 'Carolina Farias (Teste Incompleto)',
    email: 'c***s@email.com',
    phone: '(11) 9****-9999',
    experienceYears: 0,
    level: 'Estágio',
    technicalSkills: [], // Dados incompletos para testar RG06 e RG07
    bio: 'Estudante de Ciência da Computação iniciando carreira.',
    hasResume: false,
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  }
];

export const INITIAL_REVIEWS: HumanReview[] = [
  {
    id: 'rev-01',
    jobId: 'vaga-01',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    score: 100,
    status: 'Aprovado para próxima etapa',
    reviewerName: 'Ana Paula Recrutadora',
    reviewerRole: 'Recrutador',
    notes: 'Candidato com 100% de matching técnico. Experiência de 6 anos excede os 5 anos requeridos. Currículo demonstra excelente domínio em Next.js App Router.',
    technicalFeedback: 'Aprovado para entrevista técnica com o Tech Lead.',
    reviewedAt: '2026-08-26T14:30:00Z',
    createdAt: '2026-08-26T14:30:00Z',
    updatedAt: '2026-08-26T14:30:00Z',
  },
  {
    id: 'rev-02',
    jobId: 'vaga-01',
    candidateId: 'cand-02',
    candidateName: 'Mariana Costa',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    score: 85,
    status: 'Revisado',
    reviewerName: 'Ana Paula Recrutadora',
    reviewerRole: 'Recrutador',
    notes: 'Boa compatibilidade técnica (85%). Faltou Tailwind CSS no perfil explícito, porém tem sólido conhecimento em Next e TypeScript. Nível Pleno vs Sênior exigido.',
    technicalFeedback: 'Manter no radar para alinhamento de expectativas de senioridade.',
    reviewedAt: '2026-08-26T15:00:00Z',
    createdAt: '2026-08-26T15:00:00Z',
    updatedAt: '2026-08-26T15:00:00Z',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    action: 'JOB_CREATED',
    timestamp: '2026-08-15T10:00:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    weightsUsed: { 'React': 30, 'Next.js': 25, 'TypeScript': 20, 'Tailwind CSS': 15, 'Git': 10 },
    actor: { name: 'Ana Paula Recrutadora', role: 'Recrutador' },
    details: 'Vaga cadastrada com 5 competências técnicas configuradas totalizando 100% de peso.',
    immutableHash: 'a1b2c3d4e5f67890123456789abcdef012345678'
  },
  {
    id: 'aud-02',
    action: 'MATCHING_CALCULATED',
    timestamp: '2026-08-26T08:35:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    score: 100,
    classification: 'ALTA',
    matchedSkills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Git'],
    missingSkills: [],
    weightsUsed: { 'React': 30, 'Next.js': 25, 'TypeScript': 20, 'Tailwind CSS': 15, 'Git': 10 },
    actor: { name: 'Sistema IT Matcher', role: 'Sistema' },
    details: 'Cálculo de Smart Matching executado. Score: 100% (Alta compatibilidade).',
    immutableHash: 'f0e9d8c7b6a543210987654321fedcba09876543'
  },
  {
    id: 'aud-03',
    action: 'REVIEW_UPDATED',
    timestamp: '2026-08-26T14:30:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    score: 100,
    classification: 'ALTA',
    previousStatus: 'Pendente de revisão',
    newStatus: 'Aprovado para próxima etapa',
    actor: { name: 'Ana Paula Recrutadora', role: 'Recrutador' },
    details: 'Revisão humana realizada. Status atualizado para "Aprovado para próxima etapa". Decisão humana registrada com sucesso.',
    immutableHash: '11223344556677889900aabbccddeeff11223344'
  }
];
